# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-DB2
version:      0.03
version_from: lib/DateTime/Format/DB2.pm
installdirs:  site
requires:
    DateTime:                      0
    DateTime::Format::Builder:     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
